CRC Code Charts
weichware-10/meilensteine pull request #21
Opened 2021-10-29 13:12 UTC by grenoui11e

- [x] Initiale Exploration:
    - [x] Klassen finden, Verantwortlichkeiten, Zusammenarbeit
    - [x] Nomen Phrasen aufschreiben
    - [x] Alle möglichen Klassen auswählen und als CRC-Karten dokumentieren
    - [x] Verfeinern der Kandidatenliste. Hinweise:
- [x] Detaillierte Analyse
    - [x] gemeinsame Verantwortlichkeiten ⇒ Klassenhierarchien
    - [x] Konkretisierung der Kollaboration
    - [x] Abstrakte Klassen und Vererbung

2021-10-29 19:52 UTC, joshuajeschek commented
[![](https://media.discordapp.net/attachments/707505654218358818/903732869686526022/unknown.png)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
xd Danke

2021-10-31 15:43 UTC, sar-sturm commented on meilenstein_02/analyse_code-charts/exploration-code_charts.md
> +
```suggestion
- Eingabe in das Tutorialfenster (don't show again / schließen)
```

2021-10-31 15:44 UTC, sar-sturm commented on meilenstein_02/analyse_code-charts/exploration-code_charts.md
> +
```suggestion
- Tutorial
```

2021-10-31 15:47 UTC, joshuajeschek commented on meilenstein_02/analyse_code-charts/exploration-code_charts.md
> +
schön dass du jetzt deinen eigenen PR reviewst, anstatt das Zeug einfach abzuändern xd

2021-10-31 16:18 UTC, sar-sturm commented on meilenstein_02/analyse_code-charts/exploration-code_charts.md
> +
ähm ja, ich hab da unter umständen etwas durcheinandergebracht damnit

2021-11-01 22:03 UTC, joshuajeschek commented on meilenstein_02/analyse_code-charts/README.md
> +<!-- Eyetracking von Wish! -->
xd

2021-11-01 22:05 UTC, grenoui11e commented on meilenstein_02/analyse_code-charts/README.md
> +<!-- Eyetracking von Wish! -->
ist halt auch einfach ein Fakt xD

2021-11-01 22:08 UTC, joshuajeschek requested changes
ChartsInternerSpeicher ist nicht gleichmäßig benannt, würde den Unterstrich entfernen wo er noch ist

2021-11-01 22:11 UTC, joshuajeschek commented on .gitignore
> +.DS_Store
```suggestion
.DS_Store

```
Leerzeile am Dateiende

2021-11-01 22:14 UTC, grenoui11e reviewed
Done

2021-11-01 22:35 UTC, joshuajeschek requested changes

2021-11-01 22:35 UTC, joshuajeschek commented on meilenstein_02/analyse_code-charts/README.md
> +- wenn realtive Größe eingestellt, muss nach vorherigen Imputs geschaut werden
```suggestion
- wenn relative Größe eingestellt, muss nach vorherigen Imputs geschaut werden
```

2021-11-01 23:02 UTC, grenoui11e reviewed
hoffentlich fertig

2021-11-01 23:05 UTC, grenoui11e reviewed
Done

2021-11-01 23:34 UTC, joshuajeschek approved these changes
Meinerseits passt das so, jetzt ist nur noch @Rotwolf dran

2021-11-02 10:19 UTC, Rotwolf approved these changes
Top👍

2021-11-02 10:21 UTC, merged