Uml code charts
weichware-10/meilensteine pull request #37
Opened 2021-11-05 15:20 UTC by grenoui11e

2021-11-08 07:35 UTC, joshuajeschek commented on meilenstein_03/uml-code_charts/README.md
> +# UML Diagramm {Modul}
```suggestion
# UML Diagramm CodeCharts
```

2021-11-08 07:35 UTC, joshuajeschek commented on meilenstein_03/uml-code_charts/README.md
> +![Diagram]({modul}.svg)
```suggestion
![Diagram](code_charts.svg)
```

2021-11-08 07:37 UTC, joshuajeschek reviewed
Für die Verlinkung ^^

2021-11-08 09:24 UTC, Rotwolf commented
Danke, jetzt sollte alles Verlinkt sein.

2021-11-09 09:43 UTC, joshuajeschek commented
MMMmh, niemand anders hat die Dateinamen mit `uml` geprefixed, und ich denke das ist redundant...

2021-11-09 09:45 UTC, joshuajeschek requested changes
- [x] Die schon implementierten Funktionen der Tutorial-Klasse stehen noch in Zoom-Tutorial drin, da sollte nur `tutorial()` drin stehen
- [ ] Das Gleiche gilt auch bei CodeChartsBild
- [ ] Was meinst du mit dem Kommentar? Wieso bist du dir unsicher ob man es vorher laden sollte? Das macht die abstrakte Klasse und ist dazu gedacht um das Bild zB von einem Webserver auf die lokale Machine zu holen

2021-11-09 13:45 UTC, Rotwolf commented
Da das Anzeigen der verschiedenen Stufen (erst nichts, dann Bild, dann Raster, dann Eingabe Feld) Zeitkritisch nach Config Datei ablaufen muss wollten wir alle erforderlichen Daten aus der Config vorher in die einzellnen Klassen laden um keine verzögerungen zu haben.

2021-11-09 14:57 UTC, sar-sturm commented
Seht ihr die png Datei von codecharts commented auch nur rechts abgeschnitten?

2021-11-09 15:04 UTC, grenoui11e commented
Ja, das liegt aber am dem Bot

2021-11-09 15:24 UTC, sar-sturm commented
Soll der interne Speicher raus? Weil bei der kommentierten Version ist der noch drin und in der Anderen nicht

2021-11-09 17:47 UTC, joshuajeschek commented
> Seht ihr die png Datei von codecharts commented auch nur rechts abgeschnitten?

xd da ist unten ein Slider, das Bild ist vollständig @sar-sturm @grenoui11e

2021-11-09 17:48 UTC, Rotwolf commented
Naja wird Coordinator zu mächtig wenn er sich um den Speicher kümmert?
Selbst wenn wir den Speicher wieder einfügen, sollte alle Kommunikation über Coordinator laufen um die Komplexität zu verringern?
Fragen über fragen

2021-11-09 18:15 UTC, sar-sturm commented
> > Seht ihr die png Datei von codecharts commented auch nur rechts abgeschnitten?
> 
> xd da ist unten ein Slider, das Bild ist vollständig @sar-sturm @grenoui11e

Mein Slider geht nur bis zum abgeschnittenen, das ist das problem XD

2021-11-09 20:18 UTC, joshuajeschek commented
> > > Seht ihr die png Datei von codecharts commented auch nur rechts abgeschnitten?
> > 
> > 
> > xd da ist unten ein Slider, das Bild ist vollständig @sar-sturm @grenoui11e
> 
> Mein Slider geht nur bis zum abgeschnittenen, das ist das problem XD

xd weird

2021-11-09 20:42 UTC, joshuajeschek approved these changes

2021-11-09 20:42 UTC, joshuajeschek commented
braucht review von @sar-sturm

2021-11-09 21:16 UTC, sar-sturm approved these changes
![image](https://user-images.githubusercontent.com/83303430/141005927-11212c00-02f5-4ba1-9246-0be6b603d175.png)

2021-11-09 21:35 UTC, merged