UML Speichermedium
weichware-10/meilensteine pull request #38
Opened 2021-11-07 17:03 UTC by justinexner

2021-11-08 06:39 UTC, joshuajeschek commented
Sieht erstmal nicht schlecht aus.
- [ ] Ich würde vielleicht, der Übersicht halber, vorschlagen dass wir die Verbindung von dem Data Interface zu den einzelnen Tools weglassen
- [ ] Und auch zwischen AnalyseClient und SpeicherUtilities ist noch eine doppelte Verbindung, änder das mal zu einer Verbindung zu der Klasse, nicht zu 2 Funktionen der Klasse
- [ ] SpeicherUtilitys -> SpeicherUtilities

2021-11-09 15:07 UTC, grenoui11e approved these changes

2021-11-09 20:40 UTC, joshuajeschek commented
braucht Review von @Rotwolf

2021-11-09 21:14 UTC, Rotwolf approved these changes
Top

2021-11-09 21:16 UTC, Nilrei requested changes
saveData: void zu boolean (erfolgreich/nicht erfolgreich)

2021-11-09 21:18 UTC, Nilrei approved these changes

2021-11-09 21:19 UTC, merged