Usecase eye tracking
weichware-10/meilensteine pull request #60
Opened 2021-11-22 19:58 UTC by Rotwolf

2021-11-22 20:41 UTC, grenoui11e approved these changes

2021-11-22 22:38 UTC, Nilrei submitted a review, later dismissed

2021-11-23 09:45 UTC, joshuajeschek requested changes
bitte noch kurz warten 😚

2021-11-23 10:16 UTC, joshuajeschek commented
@Rotwolf der Fehler den du gemacht hast, war dass du von code charts aus checkout gemacht hast, nicht von main aus
@Nilrei wieso hast du deinen eigenen PR reviewed?

2021-11-23 10:21 UTC, joshuajeschek submitted a review, later dismissed
hier müssen wir heute abend nochmal drüber schauen, was das `<<include>> <<extend>>` zeug angeht

2021-11-23 18:08 UTC, justinexner approved these changes
Meeeeeeh

2021-11-23 18:32 UTC, merged